# Generated by Django 4.0.6 on 2022-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linktree'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktree',
            name='link',
            field=models.URLField(default='https://www.betburger.com/', max_length=255),
        ),
    ]
